[build]
  base = "artifacts/students-week"
  publish = "dist/public"
  command = "pnpm build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefix=../.."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
